export const TODAY_CHECKIN_OPTIONS_REQUEST = "TODAY_CHECKIN_OPTIONS_REQUEST";
export const TODAY_CHECKIN_OPTIONS_SUCCESS = "TODAY_CHECKIN_OPTIONS_SUCCESS";
export const TODAY_CHECKIN_OPTIONS_FAIL = "TODAY_CHECKIN_OPTIONS_FAIL";

export const CHECKIN_REQUEST = "CHECKIN_REQUEST";
export const CHECKIN_SUCCESS = "CHECKIN_SUCCESS";
export const CHECKIN_FAIL = "CHECKIN_FAIL";
export const CHECKIN_RESET = "CHECKIN_RESET";

export const MY_ATTENDANCE_REQUEST = "MY_ATTENDANCE_REQUEST";
export const MY_ATTENDANCE_SUCCESS = "MY_ATTENDANCE_SUCCESS";
export const MY_ATTENDANCE_FAIL = "MY_ATTENDANCE_FAIL";

export const CLEAR_ERRORS = "CLEAR_ERRORS";
