export const ALL_CLASS_REQUEST = "ALL_CLASS_REQUEST";
export const ALL_CLASS_SUCCESS = "ALL_CLASS_SUCCESS";
export const ALL_CLASS_FAIL = "ALL_CLASS_FAIL";

export const ADMIN_CLASS_REQUEST = "ADMIN_CLASS_REQUEST";
export const ADMIN_CLASS_SUCCESS = "ADMIN_CLASS_SUCCESS";
export const ADMIN_CLASS_FAIL = "ADMIN_CLASS_FAIL";

export const NEW_CLASS_REQUEST = "NEW_CLASS_REQUEST";
export const NEW_CLASS_SUCCESS = "NEW_CLASS_SUCCESS";
export const NEW_CLASS_FAIL = "NEW_CLASS_FAIL";
export const NEW_CLASS_RESET = "NEW_CLASS_RESET";

export const CLASS_DETAILS_REQUEST = "CLASS_DETAILS_REQUEST";
export const CLASS_DETAILS_SUCCESS = "CLASS_DETAILS_SUCCESS";
export const CLASS_DETAILS_FAIL = "CLASS_DETAILS_FAIL";

export const NEW_REVIEW_REQUEST = "NEW_REVIEW_REQUEST";
export const NEW_REVIEW_SUCCESS = "NEW_REVIEW_SUCCESS";
export const NEW_REVIEW_FAIL = "NEW_REVIEW_FAIL";
export const NEW_REVIEW_RESET = "NEW_REVIEW_RESET";

export const DELETE_CLASS_REQUEST = "DELETE_CLASS_REQUEST";
export const DELETE_CLASS_SUCCESS = "DELETE_CLASS_SUCCESS";
export const DELETE_CLASS_FAIL = "DELETE_CLASS_FAIL";
export const DELETE_CLASS_RESET = "DELETE_CLASS_RESET";

export const UPDATE_CLASS_REQUEST = "UPDATE_CLASS_REQUEST";
export const UPDATE_CLASS_SUCCESS = "UPDATE_CLASS_SUCCESS";
export const UPDATE_CLASS_FAIL = "UPDATE_CLASS_FAIL";
export const UPDATE_CLASS_RESET = "UPDATE_CLASS_RESET";

export const ALL_REVIEW_REQUEST = "ALL_REVIEW_REQUEST";
export const ALL_REVIEW_SUCCESS = "ALL_REVIEW_SUCCESS";
export const ALL_REVIEW_FAIL = "ALL_REVIEW_FAIL";

export const DELETE_REVIEW_REQUEST = "DELETE_REVIEW_REQUEST";
export const DELETE_REVIEW_SUCCESS = "DELETE_REVIEW_SUCCESS";
export const DELETE_REVIEW_FAIL = "DELETE_REVIEW_FAIL";
export const DELETE_REVIEW_RESET = "DELETE_REVIEW_RESET";

export const CLEAR_ERRORS = "CLEAR_ERRORS";
