export const CREATE_MEMBERSHIP_REQUEST = "CREATE_MEMBERSHIP_REQUEST";
export const CREATE_MEMBERSHIP_SUCCESS = "CREATE_MEMBERSHIP_SUCCESS";
export const CREATE_MEMBERSHIP_FAIL = "CREATE_MEMBERSHIP_FAIL";

export const MY_MEMBERSHIP_REQUEST = "MY_MEMBERSHIP_REQUEST";
export const MY_MEMBERSHIP_SUCCESS = "MY_MEMBERSHIP_SUCCESS";
export const MY_MEMBERSHIP_FAIL = "MY_MEMBERSHIP_FAIL";

export const MEMBERSHIP_DETAILS_REQUEST = "MEMBERSHIP_DETAILS_REQUEST";
export const MEMBERSHIP_DETAILS_SUCCESS = "MEMBERSHIP_DETAILS_SUCCESS";
export const MEMBERSHIP_DETAILS_FAIL = "MEMBERSHIP_DETAILS_FAIL";

export const ALL_MEMBERSHIPS_REQUEST = "ALL_MEMBERSHIPS_REQUEST";
export const ALL_MEMBERSHIPS_SUCCESS = "ALL_MEMBERSHIPS_SUCCESS";
export const ALL_MEMBERSHIPS_FAIL = "ALL_MEMBERSHIPS_FAIL";

export const UPDATE_MEMBERSHIP_REQUEST = "UPDATE_MEMBERSHIP_REQUEST";
export const UPDATE_MEMBERSHIP_SUCCESS = "UPDATE_MEMBERSHIP_SUCCESS";
export const UPDATE_MEMBERSHIP_FAIL = "UPDATE_MEMBERSHIP_FAIL";
export const UPDATE_MEMBERSHIP_RESET = "UPDATE_MEMBERSHIP_RESET";

export const DELETE_MEMBERSHIP_REQUEST = "DELETE_MEMBERSHIP_REQUEST";
export const DELETE_MEMBERSHIP_SUCCESS = "DELETE_MEMBERSHIP_SUCCESS";
export const DELETE_MEMBERSHIP_FAIL = "DELETE_MEMBERSHIP_FAIL";
export const DELETE_MEMBERSHIP_RESET = "DELETE_MEMBERSHIP_RESET";

export const CLEAR_ERRORS = "CLEAR_ERRORS";
