export const ADD_PROGRESS_REQUEST = "ADD_PROGRESS_REQUEST";
export const ADD_PROGRESS_SUCCESS = "ADD_PROGRESS_SUCCESS";
export const ADD_PROGRESS_FAIL = "ADD_PROGRESS_FAIL";
export const ADD_PROGRESS_RESET = "ADD_PROGRESS_RESET";

export const MY_PROGRESS_REQUEST = "MY_PROGRESS_REQUEST";
export const MY_PROGRESS_SUCCESS = "MY_PROGRESS_SUCCESS";
export const MY_PROGRESS_FAIL = "MY_PROGRESS_FAIL";

export const DELETE_PROGRESS_REQUEST = "DELETE_PROGRESS_REQUEST";
export const DELETE_PROGRESS_SUCCESS = "DELETE_PROGRESS_SUCCESS";
export const DELETE_PROGRESS_FAIL = "DELETE_PROGRESS_FAIL";
export const DELETE_PROGRESS_RESET = "DELETE_PROGRESS_RESET";

export const CLEAR_ERRORS = "CLEAR_ERRORS";
